name: heatmap-iot-analytics
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - pyspark=3.5.4
  - pandas
  - pyyaml
  - openjdk=17.0.14
  - python=3.9.21
  - bson
  - pymongo=4.11
  - geojson=3.2.0
  - openssl